/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElBacktop: typeof import("element-plus/es")["ElBacktop"];
    ElBadge: typeof import("element-plus/es")["ElBadge"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElColorPicker: typeof import("element-plus/es")["ElColorPicker"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    ElTour: typeof import("element-plus/es")["ElTour"];
    ElTourStep: typeof import("element-plus/es")["ElTourStep"];
    ElWatermark: typeof import("element-plus/es")["ElWatermark"];
  }
}
